name: Go
on: [push]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-16.04
    env:
      GITHUB_WORKFLOW: default
    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Setup go version
      uses: actions/setup-go@v1
      with:
        go-version: 1.10.4

    - name: Build snapd dependencies
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt -o Dpkg::Progress-Fancy=false update
        sudo apt -o Dpkg::Progress-Fancy=false build-dep snapd

    - name: Run unit static and unit tests
      run: |
        set -ex
        
        export GOPATH="${HOME}/gopath"
        export PATH="${PATH}:${GOPATH%%:*}/bin"
        mkdir -p "${GOPATH}/src/github.com/snapcore/"
        ln -s "$(pwd)" "${GOPATH}/src/github.com/snapcore/snapd"
        cd "${GOPATH}/src/github.com/snapcore/snapd"

        ./get-deps.sh
        ./run-checks --static
        ./run-checks --short-unit

    - name: Run integration tests
      env:
        SPREAD_GOOGLE_KEY: ${{ secrets.SPREAD_GOOGLE_KEY }}
      run: |
        set -ex

        export GOPATH="${HOME}/gopath"
        export PATH="${PATH}:${GOPATH%%:*}/bin"
        sudo apt -o Dpkg::Progress-Fancy=false install -y xdelta3
        ./run-checks --spread-ubuntu
